### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by EastRane** [HydrolienF/VoidWorldGenerator#1]
Hi! I'm using Paper 1.20.4-497 & VoidWorldGenerator 1.2.0 (updating from 1.1.4). Doesn't seem to work anymore. 1.1.4 works fine.

[00:03:45] [Server thread/INFO]: [VoidWorldGenerator] Enabling VoidWorldGenerator v1.2.0
[00:03:45] [Server thread/ERROR]: Error occurred while enabling VoidWorldGenerator v1.2.0 (Is it up to date?)
java.lang.NoClassDefFoundError: io/papermc/paper/registry/RegistryAccess
	at fr.formiko.voidworldgenerator.VoidWorldGeneratorPlugin.onEnable(VoidWorldGeneratorPlugin.java:30) ~[VoidWorldGenerator-1.2.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-497]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.papermc.paper.registry.RegistryAccess
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 11 more

**Comment by HydrolienF** [comment]
Hi @EastRane 
Thanks for repporting this issue, I hadn't tested the last version with Minecraft 1.20.4 and I added an 1.20.6+ feature to the 1.2.0 plugin version.
it's fixed with the 1.3.0 release.
